### ISSUE TITLE
Page loads then disappears

### ISSUE THREAD

**Issue by Hannah-GBS** [patrickmaher/Enhanced-RT#11]
On Firefox 70.0.1
As of yesterday, it looks like something changed on the RT site or with Firefox. When I load or refresh the Recently Added page, I see the video grid for a split second, before it's replaced by RT's "No page found" graphic. I'm no expert in these things, but the console spits out this on load: 
`TypeError: document.getElementsByClassName(...)[0] is undefined`
Which it claims is at line 1146 of the script. Not sure if that was already happening before the page stopped working though.

**Comment by KatPad** [comment]
I'm having exactly the same issue on CHROME. Edge and Firefox also.

**Comment by voronalis** [comment]
I'm getting the same issue on Chrome.

**Comment by patrickmaher** [comment]
Thanks for the report. Sorry for the delay. Somehow RT Engineering always knows when I am on vacation. It seems that whenever I go out of town they decide to make a change that will break the extension.

I'm working on it now. It should be resolved soon.
