### ISSUE TITLE
Watched videos no longer marked

### ISSUE THREAD

**Issue by Hannah-GBS** [patrickmaher/Enhanced-RT#14]
I'm assuming something in RT's back-end has changed.

Since you've said `I am still committed to maintaining the Recently Added page if/when it breaks.`, hopefully you can find time to look at this in the near future.

Just over a year without breaking is kinda neat tho

**Comment by patrickmaher** [comment]
Thank you for the report. I will take a look at it soon.

**Comment by patrickmaher** [comment]
@Hannah-GBS, thanks again for the report. I have identified the problem and a fix will be released shortly. Sorry for the delay.
