### ISSUE TITLE
Multiple Thumbnails for Videos

### ISSUE THREAD

**Issue by BRB1993** [patrickmaher/Enhanced-RT#15]
I noticed earlier that the videos in the Recently Added section now have the same thumbnails multiple times. I've checked other videos on the Rooster Teeth website that aren't affected by Enhanced RT and they don't have this issue. I've attached an image to give you an idea to what I mean. It's not a huge problem, but it's still confusing as heck.

![Multiple Thumbnails](https://user-images.githubusercontent.com/55208213/118780721-ade2e000-b8cf-11eb-9f3e-dbe7a6f94c99.png)

**Comment by Hannah-GBS** [comment]
Same issue here as of (I think) yesterday.

Bandaided it with a css fix using the Stylus extension.

**Comment by patrickmaher** [comment]
@BRB1993 Thanks for the bug report. Working on it now.
