### ISSUE TITLE
Recently added - Content Not Found

### ISSUE THREAD

**Issue by BRB1993** [patrickmaher/Enhanced-RT#16]
G'day again. Another problem has popped up with Enhanced RT. This time, the recently added section comes up with "content not found". I hope it'll be fixed soon. Thanks!
![Untitled1](https://user-images.githubusercontent.com/55208213/126438114-af8c51d7-8adc-475a-9a01-09c1414e8e30.png)

**Comment by voronalis** [comment]
I'm getting the same error using Opera GX

**Comment by patrickmaher** [comment]
Thank you for the report @BRB1993. I'm taking a look at it now. Hopefully it will be an easy fix.
