### ISSUE TITLE
Page appears briefly and then disappears

### ISSUE THREAD

**Issue by mattpow** [patrickmaher/Enhanced-RT#4]
Starting today within the past few hours 11:00 PST (18:00 UTC), the page has stopped functioning properly. Elements will briefly display until disappearing instantly. 

Multiple 404 errors and ```Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.```

**Comment by elijahorr** [comment]
Are you referencing the recently added page? I came to report this bug as you described with the recently added page

**Comment by mattpow** [comment]
Whoops! I guess I did fail to mention it is the Recently Added page. I know this extension features more but that is my primary use

**Comment by elijahorr** [comment]
me too, I will not raise another issue in this case.

**Comment by patrickmaher** [comment]
Thanks for the information. RT Engineering made a change to the page that Enhanced RT uses for its Recently Added page. Fix will be available shortly.
