### ISSUE TITLE
Recently Added - Failure August 2019

### ISSUE THREAD

**Issue by Countryen** [patrickmaher/Enhanced-RT#8]
Hey there, just noticed that since today the Recently Added page just shows an error.
This already happened some time before and they probably changed something again.

https://roosterteeth.com/watch/recently-added
Shows the "Log in..." screen below
![image](https://user-images.githubusercontent.com/11256873/62167610-e6dd4980-b323-11e9-87f8-e640b9ef495f.png)

(Note: I tried logging in, doesn't change it)

It was working just a few hours ago.

Anyone the same problem?

**Comment by stevencrader** [comment]
It seems like Rooster Teeth now displays that banner on all non-existent pages.

Ex: https://roosterteeth.com/watch/nothere shows the same.

**Comment by TaylerUva** [comment]
> It seems like Rooster Teeth now displays that banner on all non-existent pages.
> 
> Ex: https://roosterteeth.com/watch/nothere shows the same.

Only for /watch web pages. Without the /watch, it goes to the old page not found

Ex: https://roosterteeth.com/nothere

**Comment by TaylerUva** [comment]
Switching /episode URLs to /watch URLs seems to fix the issue. I have made a new pull request with this change.

**Comment by patrickmaher** [comment]
Sorry for the delay. I am in the middle of moving and I don't have an internet connection at the moment. I should be able to take a look at this tomorrow night.

**Comment by patrickmaher** [comment]
It appears that Rooster Teeth decided to abandon /episode and switched to /watch. All /episode URLs redirect to /watch. Thanks to Tayler for the fix.

I might change the location of the Recently Added page in the future. Hopefully if I move it to a page that exists, there will be less of these type of issues. I'm thinking the Recently Added page should move to roosterteeth.com/episodes and replace the episodes page.
